[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
priority=10
stdout_logfile=/var/log/nginx/nginx-stdout.log
stderr_logfile=/var/log/nginx/nginx-stderr.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB

[program:php-fpm]
command=/usr/sbin/php-fpm7.4 -F
autostart=true
autorestart=true
priority=5
stdout_logfile=/var/log/php-fpm-stdout.log
stderr_logfile=/var/log/php-fpm-stderr.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
